packages:
  - packages/*

catalog:
  '@livestore/adapter-node': 0.4.0
  '@livestore/adapter-web': 0.4.0
  '@livestore/devtools-vite': 0.4.0
  '@livestore/livestore': 0.4.0
  '@livestore/peer-deps': 0.4.0
  '@livestore/react': 0.4.0
  '@livestore/sync-cf': 0.4.0
  '@livestore/utils': 0.4.0
  '@livestore/wa-sqlite': 0.4.0
  effect: ^3.21.2
  typescript: ^6.0.3
  '@types/node': ^25.9.1
  tsx: ^4.22.3
  vitest: ^4.1.7
  eslint: ^10.4.0
  prettier: ^3.8.3
  '@typescript-eslint/eslint-plugin': ^8.60.0
  '@typescript-eslint/parser': ^8.60.0
  vite: ^8.0.14
  wrangler: 4.95.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - workerd
